config/routes.rb
  Rails.application.routes.draw do
      resources :shops
      resources :users
      resources :sneakers

      root to: 'shops#index'

    # resources :shops, only: [:index, :new, :create, :show,]
    # resources :users, only: [:index, :show, :new,]
    # resources :sneakers, only: [:index, :show,]
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  belongs_to :sneaker

  # validates :user_id, presence: true
  # validates :sneaker_id, presence: true

end

app/models/sneaker.rb
class Sneaker < ApplicationRecord
  has_many :shops
  has_many :users, through: :shops

    validates :style, presence: true, uniqueness: true
    # validates :color, presence: true
    # validates :size, presence: true

#this goes in the rb file of the model
  def sneaker_info
    "#{self.style} - #{self.color} - #{self.size}"
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :shops
  has_many :sneakers, through: :shops

  validates :name, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

    def index
      @shops = Shop.all
    end

    def show
      @shop =   Shop.find(params[:id])
    end

    def new
      @shop = Shop.new
    end

    def create
      @shop = Shop.create(check_params)
      if @shop.save
        redirect_to shops_path(@shop)
      else
        render "new"
      end
    end

    def edit
      
    end

    def update
      @shop = Shop.find(params[:id])
      @shop.update(check_params)
      redirect_to shop_path(@shop)
    end

    def destroy
      @shop =   Shop.find(params[:id])
      @shop.destroy
      redirect_to shops_path

    end

private

      def check_params
        params.require(:shop).permit(:user_id, :sneaker_id)
      end

end

app/controllers/sneakers_controller.rb
class SneakersController < ApplicationController
  before_action :set_sneaker, only: [:show, :edit, :update, :destroy]

  def index
    @sneakers = Sneaker.all
  end

  def show
    # set_sneaker
    # render :show
  end

  def new
    @sneaker = Sneaker.new
  end

  def create
    @sneaker = Sneaker.create(check_params)

    if @sneaker.save
      redirect_to @sneaker
    else
      render "new"
    end
  end

  def edit
    # set_sneaker
  end

  def update
    # set_sneaker
    @sneaker.update(check_params)
    redirect_to sneaker_path(@sneaker)
  end

  def destroy
    # set_sneaker
    @sneaker.destroy
    redirect_to sneakers_path
  end

  private

  def set_sneaker
    @sneaker = Sneaker.find(params[:id])
  end

  def check_params
    params.require(:sneaker).permit(:style, :color, :size)
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(check_params)

    if @user.save
      redirect_to @user
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(check_params)
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

private

  def check_params
    params.require(:user).permit(:name)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/sneakers_helper.rb
module SneakersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SneakerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Anton&display=swap" rel="stylesheet">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shops/edit.html.erb
<<h1>Kanyeeeee</h1>
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Adidas_Yeezy_Boost_350_Pirate_Black.gif/440px-Adidas_Yeezy_Boost_350_Pirate_Black.gif" alt="Adidas Yeezy Boost 350 Pirate Black animation.">

<%= button_to "New Shop Order", new_shop_path, method: :get%>

app/views/shops/index.html.erb
<h1>SNEAK SNEAK</h1>
<h2> Shoppe Orders</h2>

<% @shops.each do |shop|%>
<%= link_to shop.user.name, shop %>
<%= shop.sneaker.style %>
<br>
<%end%>

<br>

<%= button_to "Sneaker Index", sneakers_path, method: :get%>
<%= button_to "User Index", users_path, method: :get%>
<%= button_to "New Shop Order", new_shop_path, method: :get%>

app/views/shops/new.html.erb
  <h1>SNEAK SNEAK Shoppe!</h1>
  <h2>GET SOMETHINGS</h2>

  <%= form_for @shop do |f| %>
    <%= f.label :user_id%>
    <%= f.collection_select :user_id, User.all, :id, :name %>

    <%= f.label :sneaker_id%>
    <%= f.collection_select :sneaker_id, Sneaker.all, :id, :sneaker_info %>
    <%# f.collection_select :sneaker_id, Sneaker.all, :id, :color %>
    <%# f.collection_select :sneaker_id, Sneaker.all, :id, :size %>

    <%= f.submit text='Create Shop Order'%>

  <%end%>

  <%= button_to "Sneaker Index", sneakers_path, method: :get%>
  <%= button_to "User Index", users_path, method: :get%>
  <%= button_to "All Shop Orders", shops_path(@shop), method: :get%>

app/views/shops/show.html.erb
<h1>SNEAK SNEAK Shoppe! GET SOMETHINGS</h1>

<%= form_for @shop do |f| %>
  <%= f.label :user_id%>
  <%= f.collection_select :user_id, User.all, :id, :name %>

  <%= f.label :sneaker_id%>
  <%= f.collection_select :sneaker_id, Sneaker.all, :id, :style %>

  <%= f.submit %>
<%end%>
<%= button_to "Delete Shop Order", shop_path, method: :delete%>
<%= button_to "Sneaker Index", sneakers_path, method: :get%>
<%= button_to "User Index", users_path, method: :get%>

app/views/sneakers/edit.html.erb
<h1>👟👟👟👟👟👟👟👟Edit <%=@sneaker.style%>👟👟👟👟👟👟👟👟</h1>

  <%= form_for @sneaker do |f| %>
    <%= f.label :sneaker_id%>
    <%= f.collection_select :style, Sneaker.all, :style, :style %>
    <%= f.label :sneaker_id%>
    <%= f.collection_select :color, Sneaker.all, :color, :color %>
    <%= f.label :sneaker_id%>
    <%= f.collection_select :size, Sneaker.all, :size, :size %>
    <%= f.submit text='Edit Sneaker'%>
  <%end%>

<%= button_to "Delete Sneaker", sneaker_path, method: :delete%>
<%= button_to "Sneaker Index", sneakers_path, method: :get%>
<%= button_to "User Index", users_path, method: :get%>

app/views/sneakers/index.html.erb
<h1>👟👟👟👟👟👟👟👟Sneaker ZOOOOOONNNNNNEE👟👟👟👟👟👟👟👟👟👟</h1>

  <% @sneakers.each do |sneaker|%>
  <%= link_to sneaker.style, sneaker %>
  <%=sneaker.color %>
  <%=sneaker.size %>
  <br>
  <%end%>

<%= button_to "New Sneaker", new_sneaker_path, method: :get%>
<%= button_to "New Shop Order", new_shop_path, method: :get%>
<%= button_to "User Index", users_path, method: :get%>

app/views/sneakers/new.html.erb
<h1>⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️New Sneaker⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️</h1>

<%= form_for @sneaker do |f| %>
  Style: <%= f.text_field :style %><br />
  Color : <%= f.text_field :color %><br />
  Size : <%= f.number_field :size %><br />
  <%= f.submit %>
<% end %>
<%= button_to "Shop", new_shop_path, method: :get%>
<%= button_to "Sneaker Index", sneakers_path, method: :get%>
<%= button_to "User Index", users_path, method: :get%>

app/views/sneakers/show.html.erb
<h1>Sneaker ZOOOOOONNNNNNEE</h1>

  <%=@sneaker.style%>
  <%=@sneaker.color%>
  <%=@sneaker.size%>

  <h2>Worn by these players:</h2>

  <% @sneaker.shops.select do |shop| %>
  <%= shop.user.name %>
  <%end%>

  <%= button_to "Edit Sneaker", edit_sneaker_path(@sneaker), method: :get%>
  <%= button_to "Sneaker Index", sneakers_path, method: :get%>
  <%= button_to "User Index", users_path, method: :get%>
  <%= button_to "New Shop Order", new_shop_path, method: :get%>

app/views/users/edit.html.erb
<h1>⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️Edit <%=@user.name%>⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️</h1>

<%= form_for @user do |f| %>
  name: <%= f.text_field :name %><br/>
  <%= f.submit %>
<%end%>
<%= button_to "Sneaker Index", sneakers_path, method: :get%>
<%= button_to "User Index", users_path, method: :get%>

app/views/users/index.html.erb
<h1>👟👟👟👟👟👟👟👟Welcome Athletes, to the Sneaker Zone 👟👟👟👟👟👟</h1>
<!-- <div> -->
<h2>User List</h2>

   <% @users.each do |user| %>
      <%= link_to user.name, user %>
      <br>
    <% end %>

<!-- </div> -->
<h3>Create a new User<h3>
<%= button_to "New User", new_user_path, method: :get%>
<%= button_to "Sneaker Index", sneakers_path, method: :get%>
<%= button_to "New Shop Order", new_shop_path, method: :get%>

app/views/users/new.html.erb
  <h1>Create a New User</h1>

  <%= form_for @user do |f| %>
    name: <%= f.text_field :name %><br/>
    <%= f.submit %>
  <% end %>

  <%= button_to "Sneaker Index", sneakers_path, method: :get%>
  <%= button_to "User Index", users_path, method: :get%>

app/views/users/show.html.erb
    <h1><%=@user.name%>'s Sneaker Page</h1>

    <% @user.sneakers.each do |sneaker| %>
      <%= sneaker.style %>
      <br>
    <% end %>

    <%= button_to "Edit User", edit_user_path, method: :get %>
    <%= button_to "Delete User", user_path, method: :delete%>
    <%= button_to "Sneakers Index", sneakers_path, method: :get%>
    <%= button_to "New Shop Order", new_shop_path, method: :get%>